# Generated by Django 4.0.6 on 2022-07-19 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertable',
            name='photo',
            field=models.ImageField(upload_to='media'),
        ),
    ]
