# Generated by Django 4.0.6 on 2022-07-19 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_alter_usertable_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertable',
            name='photo',
            field=models.ImageField(upload_to='media/'),
        ),
    ]
