# Generated by Django 4.0.6 on 2022-07-19 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_alter_usertable_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertable',
            name='photo',
            field=models.ImageField(default='media/default.jpg', upload_to='media/'),
        ),
    ]
