# Generated by Django 4.0.6 on 2022-07-20 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_alter_usertable_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertable',
            name='photo',
            field=models.ImageField(blank=True, default='media/default.jpg', null=True, upload_to='media/'),
        ),
    ]
